language: php
php:
  - '7.1'
dist: trusty
sudo: required
group: edge

addons:
  sonarcloud:
    organization: "giapnd"
    token:
      secure: "2789d6ef76594de01e842403ab5d7615569b8fbd"
jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if your usnig this project as a starting point of yours
