language: php
dist: trusty
sudo: required
group: edge

addons:
  sonarcloud:
    organization: "giapnd"
    token:
      secure: "qEeQoxB95G9sApL9uNRr"

php:
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - hhvm-nightly      

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if your usnig this project as a starting point of yours
