dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "giapnd"
    token:
      secure: "1bf13cd740af6ef4843a2cce9437638d7cbe8d9a"

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if your usnig this project as a starting point of yours
