language: php
php:
  - '7.1'
dist: trusty
sudo: required
group: edge

addons:
  sonarcloud:
    organization: "webmaster"
    token:
      secure: "cae186f85e2fae94351051b37bb519f2ae871930"
jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if your usnig this project as a starting point of yours
