<?php
session_start();
$session_name=session_name();
$_SESSION=array();
if(isset($_COOKIE[$session_name])){
    setcookie($session_name,'',time()-42000);
}
session_destroy();
header('Location:session_sample_top.php');
exit;
?>
